version: "3.9"
services:
  px4_realsense_ros2:
    extends:
      file: docker-compose-gui.yml
      service: px4_realsense_ros2
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
